# Setup
title:               GilHyun's GitBlog
tagline:             ''
description:         ''
url:                 'https://pgh7659.github.io'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              PARK GILHYUN
  url:               https://github.com/pgh7659
  email:             pgh7659@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
